question_data = [
    {"question": "The Great Wall of China is the only man-made structure visible from space.", "answer": "False"},
    {"question": "Cats have nine lives.", "answer": "False"},
    {"question": "The Eiffel Tower was originally intended to be a temporary structure.", "answer": "True"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "Bananas are berries.", "answer": "True"},
    {"question": "Albert Einstein failed math in school.", "answer": "False"},
    {"question": "Elephants are the only mammals that can't jump.", "answer": "True"},
    {"question": "The Earth is flat.", "answer": "False"},
    {"question": "Coffee is made from beans.", "answer": "True"},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"question": "Tomatoes are vegetables.", "answer": "False"},
    {"question": "The Mona Lisa was painted by Leonardo da Vinci.", "answer": "True"},
    {"question": "The Statue of Liberty was a gift from France.", "answer": "True"},
    {"question": "Owls can rotate their heads 360 degrees.", "answer": "True"},
    {"question": "The Great Barrier Reef is the largest living structure on Earth.", "answer": "True"},
    {"question": "Chocolate is toxic to dogs.", "answer": "True"},
    {"question": "The Titanic was a fictional ship.", "answer": "False"},
    {"question": "Goldfish have a memory span of only 3 seconds.", "answer": "False"},
    {"question": "The moon is made of cheese.", "answer": "False"},
    {"question": "The fastest land animal is the cheetah.", "answer": "True"},
    {"question": "The capital of Australia is Sydney.", "answer": "False"},
    {"question": "Bees can recognize human faces.", "answer": "True"},
    {"question": "The Nile River is the longest river in the world.", "answer": "True"},
    {"question": "Polar bears have black skin.", "answer": "False"},
    {"question": "The Amazon rainforest produces 20% of the world's oxygen.", "answer": "True"},
    {"question": "The iPhone was first released in 2005.", "answer": "False"},
    {"question": "Birds are the only animals that can fly.", "answer": "False"},
    {"question": "Diamonds are the hardest substance on Earth.", "answer": "True"},
    {"question": "The human body has 206 bones.", "answer": "True"},
    {"question":
        "The Bermuda Triangle is a region where ships and airplanes disappear mysteriously.", "answer": "True"},
    {"question": "Mosquitoes are attracted to the color blue.", "answer": "False"},
    {"question": "The longest river in the United States is the Mississippi River.", "answer": "True"},
    {"question": "The unicorn is the national animal of Scotland.", "answer": "False"},
    {"question": "The world's largest desert is the Sahara Desert.", "answer": "True"},
    {"question": "Birds are dinosaurs.", "answer": "True"},
    {"question": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"question": "The first man to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"question": "Giraffes have the same number of neck bones as humans.", "answer": "True"},
    {"question": "The largest organ in the human body is the liver.", "answer": "True"},
    {"question": "The blue whale is the largest animal on Earth.", "answer": "True"},
    {"question": "The coldest temperature ever recorded was -128.6°F (-89.2°C).", "answer": "True"},
    {"question": "The world's smallest country is Vatican City.", "answer": "True"},
    {"question": "The Hawaiian alphabet has only 12 letters.", "answer": "True"},
    {"question": "The fastest bird in the world is the peregrine falcon.", "answer": "True"},
    {"question": "The largest volcano on Earth is Mauna Loa in Hawaii.", "answer": "True"},
    {"question": "The longest bone in the human body is the femur.", "answer": "True"},
    {"question": "Penguins can fly.", "answer": "False"},
    {"question": "The human brain stops growing at the age of 18.", "answer": "False"},
    {"question": "The capital of Brazil is Buenos Aires.", "answer": "False"},
    {"question": "Jupiter is the largest planet in our solar system.", "answer": "True"},
    {"question": "The city of Rome was built in a day.", "answer": "False"},
    {"question": "The Loch Ness Monster is a real creature.", "answer": "False"},
    {"question": "The Nile River flows through Egypt.", "answer": "True"},
    {"question": "The Mona Lisa was stolen in 1911.", "answer": "True"},
    {"question": "The world's largest ocean is the Atlantic Ocean.", "answer": "False"},
    {"question": "Olympic gold medals are made of pure gold.", "answer": "False"},
    {"question": "The human body has more than 600 muscles.", "answer": "True"},
    {"question": "Caffeine is classified as a stimulant.", "answer": "True"},
    {"question": "Bats are mammals that can see in the dark.", "answer": "True"},
    {"question": "Tigers have striped skin.", "answer": "True"},
    {"question": "The Great Wall of China is the longest wall in the world.", "answer": "True"},
    {"question": "The smallest planet in our solar system is Pluto.", "answer": "False"},
    {"question": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"question": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"question": "The smallest bone in the human body is the stirrup bone in the ear.", "answer": "True"},
    {"question": "The fastest animal on land is the cheetah.", "answer": "True"},
    {"question": "The smallest country in the world by land area is Monaco.", "answer": "True"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "The largest moon in our solar system is Ganymede.", "answer": "True"},
    {"question": "The longest muscle in the human body is the sartorius.", "answer": "True"},
    {"question": "The planet Mars is often called the Red Planet.", "answer": "True"},
    {"question": "The shortest river in the world is the Roe River in Montana, USA.", "answer": "True"},
    {"question": "The world's largest coral reef system is the Great Barrier Reef.", "answer": "True"},
    {"question": "The fastest fish in the ocean is the sailfish.", "answer": "True"},
    {"question": "The smallest bird in the world is the bee hummingbird.", "answer": "True"},
    {"question": "The highest waterfall in the world is Angel Falls in Venezuela.", "answer": "True"},
    {"question": "The smallest unit of measurement in the metric system is the millimeter.", "answer": "True"},
    {"question": "The sun is a star.", "answer": "True"},
    {"question": "The planet Neptune is the farthest planet from the sun in our solar system.", "answer": "True"},
    {"question": "The fastest land animal is the African elephant.", "answer": "False"},
    {"question": "The human eye can distinguish between approximately 10 million different colors.", "answer": "True"},
    {"question": "The largest moon in our solar system is Titan.", "answer": "False"},
    {"question": "The planet Saturn is known for its prominent rings.", "answer": "True"},
    {"question": "The longest mountain range in the world is the Andes.", "answer": "True"},
    {"question": "The smallest planet in our solar system is Mercury.", "answer": "True"},
    {"question": "The human body can survive without water for up to 3 weeks.", "answer": "False"},
    {"question": "The planet Uranus is often called the Ice Giant.", "answer": "True"},
    {"question": "The world's largest land animal is the African elephant.", "answer": "True"},
    {"question": "The longest bone in the human body is the femur.", "answer": "True"},
    {"question": "The planet Venus is often called the Morning Star.", "answer": "True"},
    {"question": "The highest mountain in Africa is Mount Kilimanjaro.", "answer": "True"},
    {"question": "The fastest bird in level flight is the common swift.", "answer": "True"},
    {"question": "The smallest ocean in the world is the Arctic Ocean.", "answer": "True"},
    {"question": "The planet Jupiter has the most moons in our solar system.", "answer": "True"},
    {"question": "The longest river in Asia is the Yangtze River.", "answer": "True"},
    {"question": "The fastest land animal is the pronghorn antelope.", "answer": "True"},
    {"question": "The world's largest bird is the ostrich.", "answer": "True"},
    {"question": "The highest mountain in North America is Denali.", "answer": "True"},
    {"question": "The smallest continent in the world is Europe.", "answer": "False"},
    {"question": "The planet Mars is often called the Red Planet.", "answer": "True"},
    {"question": "The largest planet in our solar system is Jupiter.", "answer": "True"},
    {"question": "The longest river in South America is the Amazon River.", "answer": "True"},
    {"question": "The fastest land animal is the leopard.", "answer": "False"},
    {"question": "The world's largest fish is the whale shark.", "answer": "True"},
    {"question": "The highest mountain in Europe is Mont Blanc.", "answer": "True"},
    {"question": "The planet Earth is the only known planet to support life.", "answer": "True"},
    {"question": "The smallest country in North America is Belize.", "answer": "True"},
    {"question": "The fastest land animal is the lion.", "answer": "False"},
    {"question": "The world's largest snake is the green anaconda.", "answer": "True"},
    {"question": "The highest mountain in Australia is Mount Kosciuszko.", "answer": "True"},
    {"question": "The planet Mercury is the closest planet to the sun in our solar system.", "answer": "True"},
    {"question": "The longest river in Europe is the Volga River.", "answer": "True"},
    {"question": "The fastest land animal is the kangaroo.", "answer": "False"},
    {"question": "The world's largest lizard is the Komodo dragon.", "answer": "True"},
    {"question": "The highest mountain in South America is Aconcagua.", "answer": "True"},
    {"question": "The planet Venus is often called the Evening Star.", "answer": "True"},
    {"question": "The longest river in Africa is the Nile River.", "answer": "True"},
    {"question": "The fastest land animal is the zebra.", "answer": "False"},
    {"question": "The world's largest bird of prey is the Andean condor.", "answer": "True"},
    {"question": "The highest mountain in Asia is Mount Everest.", "answer": "True"},
    {"question": "The planet Saturn is often called the Gas Giant.", "answer": "True"},
    {"question": "The longest river in North America is the Mississippi River.", "answer": "True"},
    {"question": "The fastest land animal is the cheetah.", "answer": "True"},
    {"question": "The world's largest land carnivore is the polar bear.", "answer": "True"},
    {"question": "The highest mountain in South Africa is Table Mountain.", "answer": "True"},
    {"question": "The planet Neptune is often called the Blue Planet.", "answer": "True"},
    {"question": "The longest river in Oceania is the Murray River.", "answer": "True"},
    {"question": "The fastest land animal is the gazelle.", "answer": "False"},
    {"question": "The world's largest cat is the Siberian tiger.", "answer": "True"},
    {"question": "The highest mountain in Antarctica is Mount Vinson.", "answer": "True"},
    {"question": "The planet Uranus is often called the Green Giant.", "answer": "True"},
    {"question": "The longest river in the world is the Amazon River.", "answer": "True"},
    {"question": "The fastest land animal is the horse.", "answer": "False"},
    {"question": "The world's largest land mammal is the African elephant.", "answer": "True"},
    {"question": "The highest mountain in North America is Mount McKinley.", "answer": "True"},
    {"question": "The planet Jupiter is often called the Giant Planet.", "answer": "True"},
    {"question": "The longest river in the United Kingdom is the River Severn.", "answer": "True"},
    {"question": "The fastest land animal is the jaguar.", "answer": "False"},
    {"question": "Nigeria has the largest economy in Africa.", "answer": "True"},
    {"question": "The highest point in Nigeria is Mount Kilimanjaro.", "answer": "False"},
    {"question": "The famous Osun-Osogbo Sacred Grove is located in Lagos.", "answer": "False"},
    {"question": "Nigeria has won the Africa Cup of Nations football tournament multiple times.", "answer": "True"},
    {"question": "The Nollywood film industry is named after Nigeria's capital city.", "answer": "False"},
    {"question": "The Oba of Benin is the traditional ruler of Lagos.", "answer": "False"},
    {"question": "Nigeria is home to the Zuma Rock, a famous natural landmark.", "answer": "True"},
    {"question": "The Nigerian Super Eagles is the national football team.", "answer": "True"},
    {"question": "The Nigerian film 'Lionheart' was the first African film to be nominated for an Oscar.",
     "answer": "True"},
    {"question": "Fela Kuti, the pioneer of Afrobeat music, was born in Nigeria.", "answer": "True"},
    {"question": "Lekki Conservation Centre is a wildlife reserve located in Abuja.", "answer": "False"},
    {"question": "Nigeria has a UNESCO World Heritage site called Sukur Cultural Landscape.", "answer": "True"},
    {"question": "The Nike Art Gallery in Lagos is one of the largest art galleries in Africa.", "answer": "True"},
    {"question": "Nigeria has a tropical rainforest climate.", "answer": "True"},
    {"question": "The Nigerian currency, Naira, is named after a river.", "answer": "True"},
    {"question": "The Jabi Lake is a man-made lake in Lagos.", "answer": "False"},
    {"question": "Nigeria has a thriving music industry known as Afrobeats.", "answer": "True"},
    {"question": "The annual Calabar Carnival is the largest street party in Africa.", "answer": "True"},
    {"question":
     "Nigeria has a space agency called the Nigerian National Space Research and Development Agency (NASRDA).",
     "answer": "True"},
    {"question": "The Benin Bronzes are ancient artifacts found in Nigeria.", "answer": "True"},
]
